set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'morhetz/gruvbox'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal


set background=dark	" setting dark mode
autocmd vimenter * ++nested colorscheme gruvbox

let g:airline_theme='gruvbox'
let g:airline_powerline_fonts = 1



" General
set number relativenumber		" Show hybrid line numbers
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

set linebreak				" Break lines at word (requires Wrap lines)
set showbreak=+++			" Wrap-broken line prefix
" set textwidth=100			" Line wrap (number of cols)
set showmatch				" Highlight matching brace
set visualbell				" Use visual bell (no beeping)
 
" set hlsearch				" Highlight all search results
" set smartcase				" Enable smart-case search
" set ignorecase			" Always case-insensitive
" set incsearch				" Searches for strings incrementally
 
set autoindent				" Auto-indent new lines
" set shiftwidth=4			" Number of auto-indent spaces
" set smartindent			" Enable smart-indent
" set smarttab				" Enable smart-tabs
" set softtabstop=4			" Number of spaces per Tab
"set list
"set listchars=tab:│\ ,eol:↲
 
" Advanced
set ruler				" Show row and column ruler information

set undolevels=1000			" Number of undo levels
set backspace=indent,eol,start		" Backspace behaviour

" Generated by BimConfig.com


" Colors
syntax on
" color synthetic
" color contrastneed
" color sublimemonokai


" Macros
nmap <S-CR> <S-o><Esc>j
nmap <CR> o<Esc>k


" Folding options
set foldmethod=indent
set nofoldenable
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za


" Split options
set splitbelow
set splitright


" Split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


" UTF-8 Support
set encoding=utf-8


" Make vim clipboard = OS clipboard
set clipboard=unnamed
